Help River
bethel-school-of-technology/mind-the-gap-backend pull request #4
Opened 2020-03-14 20:00 UTC by jeigsti777

River I'm not sure what to do next. @HotShot3150

2020-03-16 05:44 UTC, HotShot3150 requested changes

2020-03-16 05:44 UTC, HotShot3150 commented on models/Question.js
> +    },
When creating the schema mongoose will auto create the id field so this shouldn't be needed.

2020-03-16 05:44 UTC, HotShot3150 commented on models/Question.js
> +    }
This being the question model we do not need to have a set number of answers predefined.

Proposed Schema
QUESTION:
description : String
assessment_id : number
answership : [need to research how to setup this field] (has_many relationship)
updated_at : {type: Date, default: Date.now() }

We can discuss this further in an upcoming meeting when we go over all our schemas for the assessment.

2020-03-16 05:44 UTC, HotShot3150 commented on routes/question.route.js
> +questionRoute.route('/').get((req, res) => {
I'm not familiar with this syntax for routes. Lets meet up on this and see which routing will work best for us. Take a look at my User-Schema pull request to see what I used for the routes. Might not matter which we use.

2020-03-17 03:12 UTC, jeigsti777 commented
@HotShot3150 I updated the question model. We can talk about the routing if you have another path you want to take.

2020-03-18 04:36 UTC, merged